[package]
name = "ordinal-core"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
edition = "2018"

[dependencies]
ethnum = "1"
ark-groth16 = "0.2.0"
ark-bn254 = "0.2.0"
ark-ec = "0.2.0"
ark-ff = "0.2.0"